// Auth types
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const SET_LOADING = "SET_LOADING";
export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const USER_LOADED = "USER_LOADED";
export const USER_LOGOUT = "USER_LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const CHANGE_USER_PASSWORD = "CHANGE_USER_PASSWORD";
export const FORGOT_PASSWORD = "FORGOT_PASSWORD";
export const FORGOT_PASSWORD_VERIFICATION = "FORGOT_PASSWORD_VERIFICATION";

// Product Types
export const PRODUCT_ERROR = "PRODUCT_ERROR";
export const GET_PRODUCTS_BY_CATEGORY = "GET_PRODUCTS_BY_CATEGORY";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const FORM_LOADING = "FORM_LOADING";
export const GET_PRODUCT = "GET_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const ADD_PRODUCT_IMAGE = "ADD_PRODUCT_IMAGE";

// Basket Types
export const ADD_TO_BASKET = "ADD_TO_BASKET";
export const REMOVE_FROM_BASKET = "REMOVE_FROM_BASKET";
export const GET_BASKET = "GET_BASKET";
export const REMOVE_BASKET = "REMOVE_BASKET";
export const BASKET_LOADING = "BASKET_LOADING";
export const BASKET_ERROR = "BASKET_ERROR";
